### ISSUE TITLE
Instructions how to build unclear

### ISSUE THREAD

**Issue by wereHamster** [haskell/pvp#17]
Tried the standard cabal configure/install (using ghc 8.0.1 / cabal 2.0.0.2) but got stuck:

```
$ cabal install
Resolving dependencies...
Notice: installing into a sandbox located at
/Users/tomc/dev/pvp/.cabal-sandbox
Configuring pandoc-1.17.2...
Failed to install pandoc-1.17.2
Build log ( /Users/tomc/dev/pvp/.cabal-sandbox/logs/ghc-8.0.2/pandoc-1.17.2-5JRTd4aGtiYLtWZCoRZa7k.log ):
cabal: Entering directory '/var/folders/db/xq84lg117mj6rvv3gbj9xfkc0000gn/T/cabal-tmp-77851/pandoc-1.17.2'
cabal: Leaving directory '/var/folders/db/xq84lg117mj6rvv3gbj9xfkc0000gn/T/cabal-tmp-77851/pandoc-1.17.2'
cabal: Error: some packages failed to install:
hakyll-4.9.8.0-dHh4AOmdkYG1VA9sp85MG depends on hakyll-4.9.8.0 which failed to
install.
pandoc-1.17.2-5JRTd4aGtiYLtWZCoRZa7k failed during the configure step. The
exception was:
dieVerbatim: user error (cabal:
'/Users/tomc/.stack/programs/x86_64-osx/ghc-8.0.2/bin/ghc' exited with
an error:

/var/folders/db/xq84lg117mj6rvv3gbj9xfkc0000gn/T/cabal-tmp-77851/pandoc-1.17.2/dist/dist-sandbox-86ecebfb/setup/setup.hs:46:3:
error:
• Couldn't match expected type ‘ComponentLocalBuildInfo
-> PreProcessor’
with actual type ‘PreProcessor’
• In the expression:
PreProcessor
{platformIndependent = True,
runPreProcessor = mkSimplePreProcessor
$ \ infile outfile verbosity
-> do { let ...;
.... }}
In the expression:
\ _ lbi
-> PreProcessor
{platformIndependent = True,
runPreProcessor = mkSimplePreProcessor
$ \ infile outfile verbosity -> ...}
In the expression:
("hsb",
\ _ lbi
-> PreProcessor
{platformIndependent = True,
runPreProcessor = mkSimplePreProcessor
$ \ infile outfile verbosity -> ...})

/var/folders/db/xq84lg117mj6rvv3gbj9xfkc0000gn/T/cabal-tmp-77851/pandoc-1.17.2/dist/dist-sandbox-86ecebfb/setup/setup.hs:49:39:
error:
Data constructor not in scope: FlagName :: [Char] -> FlagName
)
pandoc-citeproc-0.10.5.1-JDDvPJ2JUou2wRNLItEWJe depends on
pandoc-citeproc-0.10.5.1 which failed to install.
pvp-site-1.0-KwEwlEDTbLx358NLFFOHpp depends on pvp-site-1.0 which failed to
install.
```

**Comment by hvr** [comment]
@wereHamster I've updated the [README](..#readme) to include some instructions. Can you try following those and see if it works then?

**Comment by wereHamster** [comment]
Can confirm that it works with GHC 8.2.1 and cabal 2.0.0.0/2.0.0.2.

I'm puzzled though why such a simple website requires the latest and greatest versions of everything. There doesn't seem to be anything that would inherently require ghc 8 or cabal 2.

**Comment by hvr** [comment]
@wereHamster It would be easy to extend support to older GHCs if that's desired, but as far as cabal is concerned, I'm dogfooding wherever I can, and given the plan to phase out the pre-`new-build` cabals as soon as possible, I have little incentive to spend the little time I have to support, test and improve tooling other than `cabal new-build`.
